sudo: false
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - postgresql

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test -Dspring.profiles.active=prod

after_success:
- curl http://www.jpm4j.org/install/script | sh
- jpm install com.codacy:codacy-coverage-reporter:assembly
- codacy-coverage-reporter -l Java -r coverage.xml
