sudo: false
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - postgresql

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test
